# Generated by Django 4.2.11 on 2024-04-10 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=100)),
                ('학번', models.CharField(max_length=100)),
                ('학과', models.CharField(max_length=100)),
                ('대회참가횟수', models.IntegerField(default=0)),
                ('총받은상금', models.IntegerField(default=0)),
                ('예상상금', models.IntegerField(default=0)),
                ('개발경력', models.TextField(blank=True, null=True)),
                ('깃주소', models.URLField(blank=True, null=True)),
                ('포토폴리오링크', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
