# Generated by Django 4.2.11 on 2024-04-29 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='연관학과',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
