# Generated by Django 4.2.11 on 2024-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_like'),
        ('users', '0005_user_연관학과'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favs',
            field=models.ManyToManyField(related_name='favs', to='contests.contest'),
        ),
    ]
