# Generated by Django 4.2.11 on 2024-05-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestapplication'),
        ('users', '0006_user_favs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apply',
            field=models.ManyToManyField(related_name='apply', to='contests.contest'),
        ),
    ]
