# Generated by Django 4.2.11 on 2024-05-23 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(null=True)),
                ('depart', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('in_school_award_cnt', models.IntegerField(null=True)),
                ('out_school_award_cnt', models.IntegerField(null=True)),
                ('national_competition_award_cnt', models.IntegerField(null=True)),
                ('certificate', models.IntegerField(null=True)),
                ('subject', models.IntegerField(null=True)),
                ('major_field', models.IntegerField(null=True)),
                ('codingTest_score', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
