# Generated by Django 4.2.11 on 2024-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_choices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
