# Generated by Django 4.2.11 on 2024-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usercontestchoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='자기소개',
            field=models.TextField(blank=True, null=True),
        ),
    ]
