# Generated by Django 4.2.11 on 2024-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_자기소개'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='subject',
            new_name='aptitude_test_score',
        ),
        migrations.AlterField(
            model_name='score',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
