# Generated by Django 4.2.11 on 2024-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_subject_score_aptitude_test_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='aptitude_test_score',
            new_name='baekjoon_score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='certificate',
            new_name='certificate_count',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='codingTest_score',
            new_name='coding_test_score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='national_competition_award_cnt',
            new_name='github_commit_count',
        ),
        migrations.RemoveField(
            model_name='score',
            name='credit',
        ),
        migrations.AddField(
            model_name='score',
            name='bootcamp_experience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='courses_taken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='programmers_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='depart',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='grade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='major_field',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], max_length=2, null=True),
        ),
    ]
