# Generated by Django 4.2.11 on 2024-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_aptitude_test_score_score_baekjoon_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='courses_taken',
            field=models.CharField(choices=[('컴퓨터공학', '컴퓨터공학'), ('인공지능', '인공지능'), ('컴퓨터 시스템 및 네트워크', '컴퓨터 시스템 및 네트워크'), ('네트워크 보안', '네트워크 보안'), ('데이터베이스', '데이터베이스'), ('웹 및 어플리케이션 개발', '웹 및 어플리케이션 개발'), ('소프트웨어 공학', '소프트웨어 공학')], max_length=50, null=True),
        ),
    ]
