# Generated by Django 4.2.11 on 2024-06-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_score_courses_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='courses_taken',
            field=models.IntegerField(choices=[(1, '컴퓨터공학'), (2, '인공지능'), (3, '컴퓨터 시스템 및 네트워크'), (4, '네트워크 보안'), (5, '데이터베이스'), (6, '웹 및 어플리케이션 개발'), (7, '소프트웨어 공학')], null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='depart',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Electrical Engineering'), (3, 'Mechanical Engineering')], null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='major_field',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Electrical Engineering'), (3, 'Mechanical Engineering')], null=True),
        ),
    ]
