# Generated by Django 4.2.11 on 2024-06-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_score_bootcamp_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='certificate_score',
            field=models.IntegerField(choices=[(1, '정보기술자격'), (2, '리눅스마스터'), (3, '데이터분석'), (4, '정보통신기사'), (5, '정보처리기사')], null=True),
        ),
    ]
