# Generated by Django 4.2.11 on 2024-06-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_score_certificate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='aptitude_test_score',
            field=models.IntegerField(null=True),
        ),
    ]
