# Generated by Django 4.2.11 on 2024-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_score_aptitude_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='senior',
            field=models.IntegerField(null=True),
        ),
    ]
