# Generated by Django 4.2.11 on 2024-06-19 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='학교',
            field=models.CharField(default=datetime.datetime(2024, 6, 19, 8, 36, 40, 470311, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
