# Generated by Django 4.2.11 on 2024-05-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='contestName',
        ),
        migrations.RemoveField(
            model_name='message',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
    ]
