# Generated by Django 4.2.11 on 2024-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_selected_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
