# Generated by Django 4.2.11 on 2024-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_conversation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
