# Generated by Django 4.2.11 on 2024-06-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_alter_conversation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
