# Generated by Django 4.2.11 on 2024-06-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0008_conversation_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='graph',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
