# Generated by Django 4.2.11 on 2024-06-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='accuracy_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='activity_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teamwork_score',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
