# Generated by Django 4.2.11 on 2024-05-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_response_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='choice',
            field=models.IntegerField(choices=[(4, '매우 그렇다'), (3, '그렇다'), (2, '보통이다'), (1, '아니다')]),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
