# Generated by Django 4.2.11 on 2024-04-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.IntegerField(null=True)),
                ('제목', models.CharField(max_length=255, null=True)),
                ('연관학과', models.CharField(max_length=100, null=True)),
                ('상금', models.CharField(blank=True, max_length=100)),
                ('학년', models.CharField(blank=True, max_length=50, null=True)),
                ('분야', models.CharField(max_length=100, null=True)),
                ('위치', models.CharField(max_length=100, null=True)),
                ('사진', models.URLField(null=True)),
                ('참고링크', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JunbukContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('related_department', models.CharField(max_length=100)),
                ('prize', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='KoreaContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('related_department', models.CharField(max_length=100)),
                ('prize', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WonkangContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('related_department', models.CharField(max_length=100)),
                ('prize', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('field', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
    ]
