# Generated by Django 4.2.11 on 2024-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
