# Generated by Django 4.2.11 on 2024-05-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_contest_상금_backup_alter_contest_상금'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='상금_backup',
        ),
        migrations.AlterField(
            model_name='contest',
            name='상금',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
