# Generated by Django 4.2.11 on 2024-05-20 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_remove_contest_상금_backup_alter_contest_상금'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='상금',
            field=models.CharField(blank=True, default=datetime.datetime(2024, 5, 20, 7, 26, 39, 475239, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
