# Generated by Django 4.2.11 on 2024-05-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_contestselection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestSelection',
        ),
    ]
