# Generated by Django 4.2.11 on 2024-06-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_response_choice_delete_choice'),
        ('contests', '0011_delete_contestselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='survey.survey'),
        ),
        migrations.AddField(
            model_name='contest',
            name='시상금',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='예측결과',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='응모분야',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='접수기간',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='접수방법',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='주최',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='참가대상',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
