# Generated by Django 4.2.11 on 2024-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_delete_contestselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='시상금',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='응모분야',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='접수기간',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='접수방법',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='주최',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contest',
            name='참가대상',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
